### ISSUE TITLE
优酷视频解析失败 20171121 开始

### ISSUE THREAD

**Issue by wnpllrzodiac** [zhangn1985/ykdl#229] opened 2017-11-22 01:02 UTC
```
YouKuDownLoader(ykdl 1.5.3), a video downloader. Forked form you-get
0.3.34@soimort

ykdl -i "http://v.youku.com/v_show/id_XMTQ4MzE2ODMwOA==.html?f=26782799&ev=1"

CRITICAL:YKDL:客户端无权播放,201
```

**Comment by mengmo** [comment] 2017-11-22 01:06
duplicate of #228
fixed by https://github.com/zhangn1985/ykdl/commit/2db6dc8eba0c38a29f1492d9829dd0aeef090277

**Closed by mengmo** 2017-11-22 01:07 UTC
